// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAleeE-rLl-DFJXzVjwyD4yv5Gec4co-ds',
    appId: '1:808882650867:web:25c847bb9e40687def0186',
    messagingSenderId: '808882650867',
    projectId: 'user-24d1f',
    authDomain: 'user-24d1f.firebaseapp.com',
    storageBucket: 'user-24d1f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBZPtMKf8wJNkoLMqICtyqtG75NQKxrgU',
    appId: '1:808882650867:android:578cb1e21e3136afef0186',
    messagingSenderId: '808882650867',
    projectId: 'user-24d1f',
    storageBucket: 'user-24d1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe7qd9fODC76555dpdTOCVunqoX44tJCo',
    appId: '1:808882650867:ios:58e88f8d75c24103ef0186',
    messagingSenderId: '808882650867',
    projectId: 'user-24d1f',
    storageBucket: 'user-24d1f.appspot.com',
    androidClientId: '808882650867-n260fsg8elftujjo4v891ijfojo1trvr.apps.googleusercontent.com',
    iosClientId: '808882650867-39jnnge0289knmeip48p14bbkrcmfrba.apps.googleusercontent.com',
    iosBundleId: 'com.example.user',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe7qd9fODC76555dpdTOCVunqoX44tJCo',
    appId: '1:808882650867:ios:58e88f8d75c24103ef0186',
    messagingSenderId: '808882650867',
    projectId: 'user-24d1f',
    storageBucket: 'user-24d1f.appspot.com',
    androidClientId: '808882650867-n260fsg8elftujjo4v891ijfojo1trvr.apps.googleusercontent.com',
    iosClientId: '808882650867-39jnnge0289knmeip48p14bbkrcmfrba.apps.googleusercontent.com',
    iosBundleId: 'com.example.user',
  );
}
